Added event action implementation

diff --git a/roles/nut_client/templates/usr/sbin/upssched-cmd.sh.j2 b/roles/nut_client/templates/usr/sbin/upssched-cmd.sh.j2
--- a/roles/nut_client/templates/usr/sbin/upssched-cmd.sh.j2
+++ b/roles/nut_client/templates/usr/sbin/upssched-cmd.sh.j2
@@ -4,7 +4,7 @@
 
 set -e
 
-# Default logging is to syslog but this can be overridden for testing
+# Default logging is to syslog but this can be overridden for testing.
  
 log="logger -i -t \"upssched-cmd\"" 
 case "${1}" in
@@ -23,13 +23,15 @@ case "${1}" in
     ;;
 esac
 
+# Heartbeat UPSs only log events, they cannot process event actions.
+
 function handle_heartbeat_event() {
   case "${2}" in
-    {% for e in nut_execute %}{{e}}{{ "|" if not loop.last else "" }}{% endfor %})
+    {% for e in nut_events %}{{e}}{{ "|" if not loop.last else "" }}{% endfor %})
       ${log} "Heartbeat Event: ${1} ${2}."
       ;;
     *)
-      ${log} "Unsupported event \"${2}\"."
+      ${log} "ERROR: Unsupported event \"${2}\"."
       ;;
   esac
 }
@@ -37,26 +39,38 @@ function handle_heartbeat_event() {
 case "${1}" in
 {% for h in groups['nut_server'] %}
 {%   for d in hostvars[h]['ups_devices'] %}
-  "ups-{{ loop.index }}@{{ h }}")
+{%     set ups="ups-" + loop.index|string + "@" +  h %}
+  "{{ ups }}")
     case "${2}" in
-{%     for e in nut_execute %}
+{%     for e in nut_events %}
       {{ e }})
-        ${log} "Handling: ups-{{ loop.index }}@{{ h }} {{e}}."
+{%       if ups in nut_actions and e in nut_actions[ups] %}
+        ${log} "Handling: {{ ups }} {{e}}."
+        {{ nut_actions[ups][e] }}
+        ${log} "Completed: {{ ups }} {{e}}. ret=$?."
+{%       else %}
+        # No action configured.
+{%       endif %}
         ;;
 {%     endfor %}
       *)
-        ${log} "Unsupported event \"${2}\"."
+        ${log} "ERROR: Unsupported event \"${2}\"."
         ;;
-      esac
+    esac
     ;;
+
 {%   endfor %}
 {%   if heartbeat_enabled %}
   "ups-H@{{ h }}")
     handle_heartbeat_event "${1}" ${2}
     ;;
+
 {%   endif %}
 {% endfor %}
   *)
-    ${log} "Unknown UPS device \"${1}\"."
+    ${log} "ERROR: Unknown UPS device \"${1}\"."
     ;;
+
 esac
+
+exit 0
